
package com.easylearnjava.webserviceprovider;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InterestCalculator", targetNamespace = "http://webserviceprovider.easylearnjava.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InterestCalculator {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     * @throws InterestException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webserviceprovider.easylearnjava.com/InterestCalculator/calculateInterestFromObjectRequest", output = "http://webserviceprovider.easylearnjava.com/InterestCalculator/calculateInterestFromObjectResponse", fault = {
        @FaultAction(className = InterestException_Exception.class, value = "http://webserviceprovider.easylearnjava.com/InterestCalculator/calculateInterestFromObject/Fault/InterestException")
    })
    public double calculateInterestFromObject(
        @WebParam(name = "arg0", partName = "arg0")
        Purchase arg0)
        throws InterestException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     * @throws InterestException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webserviceprovider.easylearnjava.com/InterestCalculator/calculateSimpleInterestRequest", output = "http://webserviceprovider.easylearnjava.com/InterestCalculator/calculateSimpleInterestResponse", fault = {
        @FaultAction(className = InterestException_Exception.class, value = "http://webserviceprovider.easylearnjava.com/InterestCalculator/calculateSimpleInterest/Fault/InterestException")
    })
    public double calculateSimpleInterest(
        @WebParam(name = "arg0", partName = "arg0")
        double arg0,
        @WebParam(name = "arg1", partName = "arg1")
        double arg1)
        throws InterestException_Exception
    ;

}
